In [1]:
print("Hello World! I am using R")

[1] "Hello World! I am using R"


In [2]:
myvar = 5

In [3]:
myvar

[1] 5

In [4]:
myvar2 <- 10
myvar2

[1] 10

In [5]:
myvar + myvar2

[1] 15

# R Guide on Youtube

http://www.newthinktank.com/2017/11/r-programming-tutorial/

In [6]:
#----- SCATTERPLOTS -----
# Use a scatterplot to see if batting average is directly
# connected to runs produced
# Load player data
mlbPlayers = read.table("https://raw.githubusercontent.com/tygithub18/Images/master/mlb2017players.txt",
                        header=T, sep=" ",
                        na.strings="`",
                        stringsAsFactors=F)

#The warning is ok. I did testing. It produces the results the way the guide does.

Warning message in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, :
“EOF within quoted string”Warning message in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, :
“number of items read is not a multiple of the number of columns”

In [7]:
# Grab just RBIs and Avg for each player
# playerData is known as a data frame (Table of Data)
# We get the stats we want by passing that list in a vector
playerData = mlbPlayers[,c("RBI","AVG")]

In [8]:
#This is how to short preview the data.
#It is similar to Python, tail works the same way.
head(playerData,10)

RBI AVG  
1   57 0.304
2   33 0.308
3   89 0.273
4  104 0.331
5   88 0.297
6   95 0.259
7  102 0.264
8  105 0.293
9  102 0.304
10  93 0.269

In [9]:
# Create the file
#It is a blank file at this point.
png(file="player_rbi_avg.png")

In [10]:
# Create the plot
plot(x=playerData$RBI, y=playerData$AVG,
     xlab="RBI", ylab="AVG", main="RBIs and Average")
 
# Create the file
#Here you input the scatter plot in to the blank file.
dev.off()

png 
  3

In [11]:
# ----- ASSIGNMENT -----
# You can assign a value using = or <-
myNum = 5
myNum

[1] 5

In [12]:
# Here are the Vector types
# numeric
print(class(4))
 
# integer
print(class(4L))

# logical (TRUE, FALSE, T, F)
print(class(TRUE))
 
# complex
print(class(1 + 4i))
 
# character
print(class("Sample"))
 
# raw when converted into raw bytes
print(class(charToRaw("Sample")))

[1] "numeric"
[1] "integer"
[1] "logical"
[1] "complex"
[1] "character"
[1] "raw"


## sprintf

Use C-style String Formatting Commands

A wrapper for the C function sprintf, that returns a character vector containing a formatted combination of text and variable values.

https://www.rdocumentation.org/packages/base/versions/3.6.0/topics/sprintf

----

This is similar to Python's magic %.

The part outisde of the quotes is the actual math.

The part in quotes is the visual print. But the % is special because it is equal to the math
after the comma.

The part after the % and before the comma is the formatting of the result.


In [13]:
# You can check an objects class with 
# is.integer(), is.numeric(), is.matrix(), is.data.frame(),
# is.logical(), is.vector(), is.character()
 
# You can convert to different classes with
# as.integer(), as.numeric(),...
 
# ----- ARITHMETIC OPERATORS -----
sprintf("4 + 5 = %d", 4 + 5)
sprintf("4 + 5 = %0.3d", 4 + 5)
sprintf("4 - 5 = %d", 4 - 5)
sprintf("4 * 5 = %d", 4 * 5)
sprintf("4 / 5 = %1.3f", 4 / 5)

[1] "4 + 5 = 9"

[1] "4 + 5 = 009"

[1] "4 - 5 = -1"

[1] "4 * 5 = 20"

[1] "4 / 5 = 0.800"

In [14]:
# Modulus or remainder of division
sprintf("5 %% 4 = %d", 5 %% 4)

[1] "5 % 4 = 1"

In [15]:
# Value raised to the exponent of the next
sprintf("4^2 = %d", 4^2)

[1] "4^2 = 16"

In [16]:
# ----- VECTORS -----
# Vectors store multiple values
# Create a vector
numbers = c(3, 2, 0, 1, 8)
numbers

[1] 3 2 0 1 8

In [17]:
# Get value by index
#This is different from Python. It starts at "1", not "0"
numbers[1]

[1] 3

In [18]:
# Get the number of items
length(numbers)

[1] 5

In [19]:
# Get the last value
#So this is tricky, he is using the get length to get the
#position of the last number, then he is calling the value of the position.
numbers[length(numbers)]

[1] 8

In [20]:
# Get everything but an index
#All, but the first number.
numbers[-1]

[1] 2 0 1 8

In [21]:
#All, but the second number.
numbers[-2]

[1] 3 0 1 8

In [22]:
# Get the first 2 values
numbers[c(1,2)]

[1] 3 2

In [23]:
# Get the 2nd and 3rd
numbers[2:3]

[1] 2 0

In [24]:
# Replace a value
#Before
numbers
numbers[5] = 1
#After
numbers

[1] 3 2 0 1 8

[1] 3 2 0 1 1

In [25]:
# Replace the 4th and 5th with 2
numbers[c(4,5)] = 2
numbers

[1] 3 2 0 2 2

In [26]:
# sort values (decreasing can be TRUE or FALSE)
sort(numbers, decreasing=TRUE)

[1] 3 2 2 2 0

In [27]:
# Generate a sequence from 1 to 10
oneToTen = 1:10
oneToTen

[1]  1  2  3  4  5  6  7  8  9 10

In [28]:
# Sequence from 3 to 27 adding 3 each time
add3 = seq(from=3, to=27, by=3)
add3

[1]  3  6  9 12 15 18 21 24 27

In [29]:
# Create 10 evens from 2
evens = seq(from=2, by=2, length.out=10)
evens

[1]  2  4  6  8 10 12 14 16 18 20

In [30]:
# Find out if a value is in vector
sprintf("4 in evens %s", 4 %in% evens)

[1] "4 in evens TRUE"

In [31]:
# rep() repeats a value/s x number of times and
# each defines how many times to repeat each item
rep(x=2, times=5, each=2)
 

#Two 1's, then two 2's, then two 3's. Then repeat it for a second time.
rep(x=c(1,2,3), times=2, each=2)


[1] 2 2 2 2 2 2 2 2 2 2

[1] 1 1 2 2 3 3 1 1 2 2 3 3

In [32]:
# ----- RELATIONAL OPERATORS -----
iAmTrue = TRUE
iAmFalse = FALSE
 
sprintf("4 == 5 : %s", 4 == 5)
sprintf("4 != 5 : %s", 4 != 5)
sprintf("4 > 5 : %s", 4 > 5)
sprintf("4 < 5 : %s", 4 < 5)
sprintf("4 >= 5 : %s", 4 >= 5)
sprintf("4 <= 5 : %s", 4 <= 5)
sprintf("5 <= 5 : %s", 5 <= 5)

[1] "4 == 5 : FALSE"

[1] "4 != 5 : TRUE"

[1] "4 > 5 : FALSE"

[1] "4 < 5 : TRUE"

[1] "4 >= 5 : FALSE"

[1] "4 <= 5 : TRUE"

[1] "5 <= 5 : TRUE"

In [33]:
# Relational operator vector tricks
oneTo20 = c(1:20)
oneTo20

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [34]:
# Create vector of Ts and Fs depending on condition
#Has a remainder of 0 when you divide by 2.
isEven = oneTo20 %% 2 == 0
isEven

[1] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
[13] FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE

In [35]:
# Create array of evens
#Give me only the values where there is a remainder of 0 when you divide by 2.
justEvens = oneTo20[oneTo20 %% 2 == 0]
justEvens

[1]  2  4  6  8 10 12 14 16 18 20

In [36]:
# ----- LOGICAL OPERATORS -----
#R Guide: https://cran.r-project.org/doc/manuals/r-release/R-lang.html#Operators
cat("TRUE && FALSE = ", T && F, "\n")#Basically look at the left side, that is the answer.
cat("TRUE || FALSE = ", T || F, "\n")#Basically look at the left side, that is the answer.
cat("!TRUE = ", !T, "\n")# This means not True because of the "!"

TRUE && FALSE =  FALSE 
TRUE || FALSE =  TRUE 
!TRUE =  FALSE 


In [37]:
# ----- DECISION MAKING -----
#It would be great to add an input box.
age = 18
 
# if, else and else if works like other languages
if(age >= 18) {
  print("Drive and Vote")
} else if (age >= 16){
  print("Drive")
} else {
  print("Wait")
}

[1] "Drive and Vote"


In [38]:
# ----- SWITCH -----
# Used when you have a limited set of possible values
grade = "Z"
 
switch(grade,
       "A" = print("Great"),
       "B" = print("Good"),
       "C" = print("Ok"),
       "D" = print("Bad"),
       "F" = print("Terrible"),
       print("No Such Grade"))

[1] "No Such Grade"


In [39]:
# ----- STRINGS -----
str1 = "This is a string"
str1

[1] "This is a string"

In [40]:
# String length
#I had to fix this
#https://stat.ethz.ch/R-manual/R-devel/library/base/html/nchar.html
nchar(str1, type = "chars")

[1] 16

In [41]:
# You can compare strings where later letters are considered
# greater than
#Think of it as bytes.
sprintf("Dog > Egg : %s", "Dog" > "Egg")
sprintf("Dog == Egg : %s", "Dog" == "Egg")

[1] "Dog > Egg : FALSE"

[1] "Dog == Egg : FALSE"

In [42]:
# Combine strings and define sperator if any
str2 = paste("Owl", "Bear", sep="")
str2

[1] "OwlBear"

In [43]:
# Remove bear from the string
substr(x=str2, start=4, stop=7)

[1] "Bear"

In [44]:
# Substitute one string with another
sub(pattern="Owl", replacement="Hawk", x=str2)

[1] "HawkBear"

In [45]:
# Substitute all matches
#I think the "g" means global.
gsub(pattern="Egg", replacement="Chicken", x="Egg of Egg")
#The x is the actualy source string.

[1] "Chicken of Chicken"

In [46]:
# Split string into vector
#This is like turning a string into a list.
strVect = strsplit("A dog ran fast", " ")
 
strVect

[[1]]
[1] "A"    "dog"  "ran"  "fast"

In [47]:
# ----- FACTORS ------
# Factors are used when you have a limited number of values
# that are strings or integers
 
# Create a factor vector
direction = c("Up", "Down", "Left", "Right", "Left", "Up")
factorDir = factor(direction)

In [48]:
# Check if it's a Factor
is.factor(factorDir)

[1] TRUE

In [49]:
# A Factor object contains levels which store all possible
# values
#This are the unique values.
levels(x=factorDir)

[1] "Down"  "Left"  "Right" "Up"

In [50]:
# You can define your levels and their orders
dow = c("Monday", "Tuesday", "Wednesday", "Thursday",
        "Friday", "Saturday", "Sunday")
 
wDays = c("Tuesday", "Thursday", "Monday")
 
wdFact = factor(x=wDays, levels=dow, ordered=T)
 
wdFact

#This is an interesting use of Levels. If you want to expand and see more.

[1] Tuesday  Thursday Monday  
7 Levels: Monday < Tuesday < Wednesday < Thursday < Friday < ... < Sunday

In [51]:
# ----- DATA FRAMES -----
# A Data Frame is a table which contains any type 
# of data and an equal amount of data in each column
 
# Each row is called a record and each column a varaible
 
# Create customer data frame
custData = data.frame(name=c("Tom", "Sally", "Sue"),
                      age=c(43, 28, 35), 
                      stringsAsFactors=F)
 
custData

name  age
1 Tom   43 
2 Sally 28 
3 Sue   35

Key: (Row, Column)

Just like Python and VBA

In [52]:
# Get data in row 1 column 1

custData[1,1]

[1] "Tom"

In [53]:
# Get all data in 1st row
custData[1,1:2]

name age
1 Tom  43

In [54]:
# Get all ages
custData[1:3, 2]

[1] 43 28 35

In [55]:
# Get dimensions
dim(custData)

[1] 3 2

In [56]:
# Add another record
recordMark = data.frame(name="Mark", age=33)
custData = rbind(custData, recordMark)
custData

name  age
1 Tom   43 
2 Sally 28 
3 Sue   35 
4 Mark  33

In [57]:
# Add a column representing debt
debt = c(0, 25.50, 36, 48.19)
custData = cbind(custData, debt)
custData

name  age debt 
1 Tom   43   0.00
2 Sally 28  25.50
3 Sue   35  36.00
4 Mark  33  48.19

In [58]:
# Check if money is owed
owesMoney = custData[custData$debt > 0,]
owesMoney

name  age debt 
2 Sally 28  25.50
3 Sue   35  36.00
4 Mark  33  48.19

In [59]:
# ----- LOOPING -----
# Repeat until a condition is met
num = 1
repeat{
  print(num)
  num = num + 1
  if(num > 5){
    
    # Jumps out of loop
    break
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [60]:
# Repeat while condition is true
#This is pulling the variable "num" from the code above.
while(num > 0){
  num = num - 1
  
  # next skips the rest of the loop and jumps
  # back to the top
  if(num %% 2 == 0){
    next
  }
  print(num)
}

[1] 5
[1] 3
[1] 1


In [61]:
# For can be used to cycle through a vector
# or do the same thing a specific number of times
oneTo5 = 1:5
for (i in oneTo5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [62]:
# ----- MATRICES -----
# A Matrix stores values in rows and columns
 
# Create a Matrix with a single column
matrix1 = matrix(data=c(1,2,3,4))
matrix1

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4

In [63]:
# Create a matrix with defined rows and columns
matrix2 = matrix(data=c(1,2,3,4), nrow=2, ncol=2)
matrix2

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [64]:
# You can also fill by row (You can use T or TRUE)
matrix3 = matrix(data=c(1,2,3,4), nrow=2, ncol=2, byrow=T)
matrix3

[,1] [,2]
[1,] 1    2   
[2,] 3    4

In [65]:
# Get a Matrix dimension
#2 rows and 2 columns.
dim(matrix3)

[1] 2 2

In [66]:
# A value at row, column
matrix3[1,2]

[1] 2

In [67]:
# Get a whole row
matrix3[1,]

[1] 1 2

In [68]:
# Get a whole column
matrix3[,2]

[1] 2 4

In [69]:
# Combine vectors to make a Matrix
matrix4 = rbind(1:3, 4:6, 7:9)
matrix4

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [70]:
# Get 2nd and 3rd row
matrix4[2:3,]

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

In [71]:
# Get 2nd and 3rd row by ommitting the 1st
matrix4[-1,]

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

In [72]:
# Change the first value
matrix4[1,1] = 0
matrix4

[,1] [,2] [,3]
[1,] 0    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [73]:
# Change the 1st row
matrix4[1,] = c(10,11,12)
matrix4

[,1] [,2] [,3]
[1,] 10   11   12  
[2,]  4    5    6  
[3,]  7    8    9

This is tricky

It is data cube. Here is what it actually looks like:

https://www.geeksforgeeks.org/multidimensional-arrays-c-cpp/

In [74]:
# ----- MULTI-DIMENSIONAL ARRAYS -----
# You can also create Matrices in layers 

# Create a MDA with 2 rows, columns and layers
array1 = array(data=1:8, dim=c(2,2,2))
array1

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

In [75]:
# Get a value
array1[1,1,2]
 
# Experiment grabbing values like we did with the Matrix
# Everything is the same

[1] 5

In [76]:
# ----- FUNCTIONS -----
# A function is R is an object that performs operations
# on passed attributes and then returns results
# or simply control back
 
getSum = function(num1, num2){
  return(num1 + num2)
}

#This is to demonstrate it as a function.
#num1 is 5
#num2 is 6
sprintf("5 + 6 = %d", getSum(5,6))

#You can also do this too.
sprintf("5 + 6 = %d", 5+6)

[1] "5 + 6 = 11"

[1] "5 + 6 = 11"

In [77]:
# If there is no return the last expression is returned
# You can define default attribute values
getDifference = function(num1=1, num2=1){
  num1 - num2
}
 
sprintf("5 - 6 = %d", getDifference(5,6))

#I would go with a traditional function, this is kinda weird.
sprintf("4 - 6 = %d", getDifference(4,6))

[1] "5 - 6 = -1"

[1] "4 - 6 = -2"

In [78]:
# Return multiple values in a list
#The seperate here is a blank space.
#Turning string into seperated list values.
makeList = function(theString){
  return (strsplit(theString, " "))
}
 
makeList("Random Words")

[[1]]
[1] "Random" "Words"

In [79]:
# Handling missing arguments
missFunc = function(x){
  if(missing(x)){
    return("Missing Argument")
  } else {
    return(x)
  }
}
 
missFunc()
missFunc(10)
#If there is nothing, then display the message.
#If there is something, display it.

[1] "Missing Argument"

[1] 10

In [80]:
# Excepting variable number of arguments with ellipses
#Just fancy stuff: ellipses
getSumMore = function(...){
  numList = list(...)
  sum = 0
  for(i in numList){
    sum = sum + i
  }
  sum
}
 
getSumMore(1,2,3,4)

[1] 10

In [81]:
# Disposable / Anonymous Functions are great for 
# quick operations like doubling everything in a list
#This is like Python Lambda
numList = 1:10
dblList = (function(x) x * 2)(numList)
dblList

[1]  2  4  6  8 10 12 14 16 18 20

In [82]:
# Closures are functions created by functions
# Create a function that finds x to a user defined
# power
power = function(exp){
  function(x){
    x ^ exp
  }
}
 
cubed = power(3)
print("2 cubed:")
cubed(2)

print("Cubing values 1 to 5")
cubed(1:5)

[1] "2 cubed:"


[1] 8

[1] "Cubing values 1 to 5"


[1]   1   8  27  64 125

In [83]:
# You can store functions in lists
addFunc = list(
  add2 = function(x) x + 2,
  add3 = function(x) x + 3
)
 
addFunc$add2(5)
addFunc$add3(5)

[1] 7

[1] 8

In [84]:
# ----- EXCEPTION HANDLING -----
# Used to gracefully handle errors
# I handle a division with string error
 
divide = function(num1, num2){
  tryCatch(
    num1 / num2,
    error = function(e) {
      if(is.character(num1) || is.character(num2)){#This is like, is not.
        print("Can't Divide with Strings")
      }
  })
}
 
divide(10,"5")

[1] "Can't Divide with Strings"


In [85]:
# ----- READING WRITING FILES -----
# Create a text file with headers fname lname sex
# and the data in a txt file Use `for missing values
# Save in the same directory as your R file
 
# Supply the file to read, whether the 1st line is 
# headers, what seperates the data, what is being used
# for missing data and false because you don't want to
# convert string vectors to factors
 
# myPeople is a data frame
myPeople = read.table("https://raw.githubusercontent.com/tygithub18/Images/master/myPeople.csv",
                      header=T, sep=",",
                      na.strings="`",
                      stringsAsFactors=F)
myPeople

fname  lname   sex   
1 Andy   Brennan male  
2 Harry  Truman  male  
3 Lucy   Moran   female
4 Dale   Cooper  male  
5 Shelly Johnson female
6 Audrey Horne   female
7 Bob    Marx    male  
8 Donna  Heyward female

In [86]:
# Add another person
donnaRecord = data.frame(fname="Donna",
                         lname="Heyward",
                         sex="female")
myPeople = rbind(myPeople, donnaRecord)

In [87]:
#Preview the data
myPeople

fname  lname   sex   
1 Andy   Brennan male  
2 Harry  Truman  male  
3 Lucy   Moran   female
4 Dale   Cooper  male  
5 Shelly Johnson female
6 Audrey Horne   female
7 Bob    Marx    male  
8 Donna  Heyward female
9 Donna  Heyward female

In [88]:
# Update a record
myPeople[7,2] = "Smith"

In [89]:
#Preview the data
#Look at Bob
myPeople

fname  lname   sex   
1 Andy   Brennan male  
2 Harry  Truman  male  
3 Lucy   Moran   female
4 Dale   Cooper  male  
5 Shelly Johnson female
6 Audrey Horne   female
7 Bob    Smith   male  
8 Donna  Heyward female
9 Donna  Heyward female

In [90]:
# Get 1st 3 records
head(myPeople, 3)

fname lname   sex   
1 Andy  Brennan male  
2 Harry Truman  male  
3 Lucy  Moran   female

In [91]:
# Get remaining records
tail(myPeople)

fname  lname   sex   
4 Dale   Cooper  male  
5 Shelly Johnson female
6 Audrey Horne   female
7 Bob    Smith   male  
8 Donna  Heyward female
9 Donna  Heyward female

In [92]:
# ----- BASIC PLOTTING -----
# R provides great plotting tools
 
# Plotting x y coordinates from a matrix
# 1st 5 are x and 2nd 5 are y
xy1 = matrix(data=c(1,2,3,4,5,
                    1,2,3,4,5), nrow=5, ncol=5)
plot(xy1)

In [93]:
# Draw a line
x2 = c(1,2,3,4,5)
y2 = c(1,2,3,4,5)
plot(x2, y2, type="l")

In [94]:
# Points and lines
plot(x2, y2, type="b")

In [95]:
# Points and lines
plot(x2, y2, type="c")

In [96]:
# Points and lines with no space around points,
# labels, a blue line (Find more with colors())
plot(x2, y2, type="o", 
     main="My Plot", xlab="x axis", ylab="y axis",
     col="steelblue")

In [97]:
# pch (1-25) defines different points
# lty (1-6) defines different lines
# xlim defines the max and min x plotting region
# ylim defines the max and min y plotting region
plot(x2, y2, type="b", pch=2, lty=2,
     xlim=c(-8,8), ylim=c(-8,8))

## Upgrading a chart

In [98]:
# Multiple plots
plot(x2, y2, type="b")

In [99]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

In [100]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

In [101]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

# Draw an arrow
arrows(x0=1.5, y0=4.55, x1=2.7, y1=3.3, col="blue")

In [102]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

# Draw an arrow
arrows(x0=1.5, y0=4.55, x1=2.7, y1=3.3, col="blue")

# Print Text
text(x=1.25, y=4.75, labels="Center")

In [103]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

# Draw an arrow
arrows(x0=1.5, y0=4.55, x1=2.7, y1=3.3, col="blue")

# Print Text
text(x=1.25, y=4.75, labels="Center")

# Load a built in data.frame
plot(faithful)

In [104]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

# Draw an arrow
arrows(x0=1.5, y0=4.55, x1=2.7, y1=3.3, col="blue")

# Print Text
text(x=1.25, y=4.75, labels="Center")

# Load a built in data.frame
plot(faithful)

# Highlight eruptions with a waiting time greater
# then 4
eruptions4 = with(faithful, faithful[eruptions > 4,])

In [105]:
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)
# Multiple plots
plot(x2, y2, type="b")
 
# Adds straight lines at 2 and 4 coordinates
abline(h=c(2,4), col="red",lty=2)

# Draw a 2 segmented lines with starting and ending x
# and y points
segments(x0=c(2,4), y0=c(2,2), x1=c(2,4), y1=c(4,4),
         col="red",lty=2)

# Draw an arrow
arrows(x0=1.5, y0=4.55, x1=2.7, y1=3.3, col="blue")

# Print Text
text(x=1.25, y=4.75, labels="Center")

# Load a built in data.frame
plot(faithful)

# Highlight eruptions with a waiting time greater
# then 4
eruptions4 = with(faithful, faithful[eruptions > 4,])

# Draw specific points
points(eruptions4, col="red", pch=3)

## End of graph

In [106]:
# ----- MATH FUNCTIONS -----
sqrt(x=100)

[1] 10

In [107]:
# Get the power you raise the base to get x
log(x=4, base=2)

[1] 2

In [108]:
# Euler's number 2.718 to the power of x
exp(x=2)

[1] 7.389056

In [109]:
# Sum all vector values
sum(c(1,2,3))

[1] 6

In [110]:
# Find the mean (average)
randD1 = c(1,5,6,7,10,16)
mean(randD1)

[1] 7.5

In [111]:
# The median (Middle Number or avg of middle 2)
median(randD1)

[1] 6.5

In [112]:
# Minimum value
min(randD1)

[1] 1

In [113]:
# Maximum value
max(randD1)

[1] 16

In [114]:
# Min and max
range(randD1)

[1]  1 16

In [115]:
# Rounding
ceiling(4.5)
floor(4.5)

[1] 5

[1] 4

In [116]:
# Cumulatives
cumsum(c(1,2,3))
cumprod(c(1,2,3))
cummax(c(7:9, 4:6, 1:3))
cummin(c(4:6, 1:3, 7:9))

[1] 1 3 6

[1] 1 2 6

[1] 7 8 9 9 9 9 9 9 9

[1] 4 4 4 1 1 1 1 1 1

In [117]:
# Generating Random samples
# Flipping a coin 10 times and weigh the probability
# of the next flip based on the previous
#1 is heads, 0 is tails
sample(0:1,10,replace=T)
 
sample(1:20,10,replace=T)

[1] 0 0 0 0 1 1 0 0 1 1

[1]  6 15  8 10 19  1 10  7  1 19

# Notes about visual

I noticed I need to split the code in order to view it using Azure Notebook. It still works, but just keep that in mind.

In [118]:
# ----- PIE CHARTS -----
# List percentages
foodPref = c(15, 35, 10, 25, 15)
 
# Labels associated with percentages
foodLabels = c("Spaghetti", "Pizza", "Mac n' Cheese",
           "Chicken Nuggets", "Tacos")
 
# Where to save the image
png(file="child_food_pref.png")

In [119]:
# Colors used for each option
colors = rainbow(length(foodPref))
 
# Create the chart
pie(foodPref, foodLabels, main="Food Prefs",
    col=colors)

In [120]:
# 3D Pie Chart
# Download package in console install.packages("plotrix")
# Get the library
library(plotrix)
 
# Name the chart file
png(file="3d_child_food_pref.png")

In [121]:
# Create the chart
pie3D(foodPref, labels=foodLabels, explode=0.1,
      start=pi/2, main="Food Prefs", labelcex=0.8)
 
# Save the chart
dev.off()

png 
  3

In [122]:
# ----- BAR CHARTS -----
# Define the bar chart file
png(file="food_pref_bar_chart.png")

In [123]:
# Plot the chart
barplot(foodPref, names.arg=foodLabels, xlab="Votes",
        ylab="Food Options", col=colors, 
        main="Food Prefs")
 
# Save File
dev.off()

png 
  3

In [124]:
# ----- REGRESSION ANALYSIS -----
# Used to study a relationship between 2 separate 
# pieces of data (What is the relation between batting
# average and RBIS)
 
# Create relationship model between AVG and RBIs
relation = lm(playerData$RBI~playerData$AVG)
 
# Create file 
png(file="RBI_AVG_Regression.png")

In [125]:
# Plot the chart
plot(playerData$AVG, playerData$RBI, 
     main="AVG & RBI Regression", 
     abline(lm(playerData$RBI~playerData$AVG)),
     xlab="AVG", ylab="RBIs")
 
# Save chart
dev.off()

png 
  3

In [126]:
# ----- MULTIPLE REGRESSION -----
# Used to study the impact on one variable from numerous 
# others
# Estimate RBIs based on other player stats
playerData2 = mlbPlayers[,c("RBI","AVG","HR","OBP",
                            "SLG","OPS")]
 
# Create the relationship model
relation2 = lm(playerData2$RBI ~ playerData2$AVG + 
                 playerData2$HR + playerData2$OBP +
                 playerData2$SLG + playerData2$OPS)
 
sprintf("Intercept : %f1.4", coef(relation2)[1])

[1] "Intercept : -5.0469831.4"

In [127]:
# How stats effect RBIs
sprintf("AVG : %f1.4", coef(relation2)[2])
sprintf("HR : %f1.4", coef(relation2)[3])
sprintf("OBP : %f1.4", coef(relation2)[4])
sprintf("SLG : %f1.4", coef(relation2)[5])
sprintf("OPS : %f1.4", coef(relation2)[6])

[1] "AVG : 372.9573421.4"

[1] "HR : 2.5640011.4"

[1] "OBP : -5.4096911.4"

[1] "SLG : -167.3732241.4"

[1] "OPS : NA1.4"

In [128]:
# Calculate expected RBIs based on stats
# Evan Longoria
# RBIs   AVG   HR   OBP   SLG   OPS
# 86     .261  20  .313  .424  .737
RBIGuess = -5.05 + (372.96 * .261) + (2.56 * 20) +
  (-5.41 * .313) + (-167.37 * .424)
RBIGuess

[1] 70.83435

# The end